- app/controllers/api/v1/medias_controller.rb
- app/controllers/concerns/medias_doc.rb
- app/models/media.rb
- config/environments/development.rb
- public/api/v1/medias.json
- test/controllers/medias_controller_test.rb
- test/models/media_test.rb
- test/test_helper.rb
As per https://mantis.meedan.com/view.php?id=5052
A few things to review:
- how to test that `refresh` is effective?
- tagged with FIXME a couple of FB tests (maybe for later)
- tagged with HACK the fact that a variable in the code is only used for tests - if that's OK, we can do the same for `refresh`.
> Optional param to force-refresh a link

- test/models/media_test.rb
Also add a test to avoid overwriting metatags with nil to replace the
removed one
> Ticket #5048: Removed test broken because the page needs login

- app/views/medias/index.js.erb
Verify if element exists before trying to get its coordinates
> Ticket #5302: Avoid js error on media.js

- app/models/concerns/media_facebook_item.rb
- app/models/concerns/media_instagram_item.rb
- test/models/media_test.rb
Get username (slug) from Facebook user profiles and pages
Get author_name from Instagram
> Ticket #5757: Get username (slug) and name from medias

- app/models/concerns/media_oembed_item.rb
- app/models/concerns/media_page_item.rb
- test/models/media_test.rb
Also, check if `article:author` is url
> Ticket #6267: Don't merge nil data from oembed with the media data

- app/models/media.rb
- test/controllers/medias_controller_test.rb
> Ticket #6256: Only notify rails logger when the url is invalid

- app/models/concerns/media_oembed_item.rb
- test/models/media_test.rb
As per https://mantis.meedan.com/view.php?id=6554
> Fix oEmbed `html` usage

- app/models/concerns/media_twitter_item.rb
- test/models/twitter_test.rb
Also allows parsing page after failing on getting the api data
> Ticket #7259: Raise only 1 errbit error when tweet is not found

- .gitlab-ci.yml
Configurator is not needed to build the container anymore.
> Removing configurator from build

- app/models/concerns/media_video_archiver.rb
- app/workers/archive_video_worker.rb
- test/models/archiver_test.rb
The subtitles/info/thumbnails/video are stored in different keys
> Ticket #6624: List archived video files grouped by type

- config/.env.example
- config/config.yml.example
- config/database.yml.example
- config/environments/production.rb
- config/environments/production.rb.example
- config/initializers/logstash_logger.rb.example
- config/sidekiq.yml.example
@danielafeitosa @caiosba plz review changes here, including:
- updated example files (including comments)
- delete files
- there are a few `.example` files that have no equivalent in `configurator` - can these be deleted too? `secret_token.rb.example` and `profile.rb.example`
> Config updates to be reviewed

- test/data/page-with-schema.html
- test/models/media_test.rb
The structure of the page changed. Mocking the page `html`
> Ticket #8185: Fix Pender test

- Dockerfile
- production/Dockerfile
Set locale to UTF-8 capable character set.
> Set locale to C.UTF-8

- test/test-coverage
Clone a specific version to avoid 'cannot find package crypto/ed25519' in the current version
References: CHECK-2236
> clone a specific code climate version

- app/models/concerns/provider_facebook.rb
- app/models/parser/base.rb
- app/models/parser/facebook_item.rb
- app/models/parser/facebook_profile.rb
- test/models/parser/facebook_item_test.rb
- test/models/parser/facebook_profile_test.rb
Addressing discrepancies in this sheet: https://docs.google.com/spreadsheets/d/1LGGySwAnzckyrZLxHXtDjTgY6vBncBHnWzA0RynB2C8/edit#gid=600307358
> Updates for Pender refactor

- app/models/concerns/media_crowdtangle_item.rb
- app/models/concerns/provider_facebook.rb
- app/models/media.rb
- app/models/parser/facebook_item.rb
- app/models/parser/facebook_profile.rb
- test/models/parser/facebook_item_test.rb
- test/models/parser/facebook_profile_test.rb
See commit messages for summary
> Additional Pender fixes

- app/models/parser/facebook_item.rb
- test/models/parser/facebook_item_test.rb
I came across this in testing.
CV2-2737
> Add new video URL pattern for Facebook item URLs

- pull_request_template.md
Added a pull request template so we can make sure we are always providing enough information and context about the pull request. I used the template in check web as a starting point.
I'm leaving the sections bellow, even though they don't necessarily apply to this ticket, just because it's a good way to see what it's currently looking like. 🙂 
References: [cv2-3157](https://meedan.atlassian.net/browse/CV2-3157?atlOrigin=eyJpIjoiN2Q2NDk4Mzg1ZWQ2NGJmMjlhMzUyNzlmZWI5OTQ4ZGEiLCJwIjoiaiJ9)
- File FFFF, line LL: This …
> CV2-3157: add pull_request_template

- CODEOWNERS
> Remove me as codeowner :)

- README.md
Manu and I decided to clarify this while pairing on the Pender Facebook parser
> Update readme documentation for parser

- app/models/parser/kwai_item.rb
Add safe operator to strip to avoid no method error.
References: 3723
> add safe operator to strip

- .gitlab-ci.yml
This change updates the docker images and utilities used during ECS deployments to QA and Live.
This change uses the same versions tested across alegre and check-api.
> Fix ECS deployments with updated utilities.

- .gitlab-ci.yml
Final fix for ECS deployments into QA and Live. Use correct awscli version.
Tested and verified a deployment into QA this time :)
> Bugfix for aws ecs deployments

- app/sidekiq/archiver_status_job.rb
Fix identation that got misaligned in this PR:
https://github.com/meedan/pender/pull/427
> 4076 – Fix Indentation

- config/routes.rb
We want to add Sidekiq's web interface so it's easier to manage queues on Pender live.
References: 4209
- Etc.
> 4209 – Add Sidekiq Interface for Pender live

- app/sidekiq/archiver_status_job.rb
- app/workers/archiver_worker.rb
- app/workers/metrics_worker.rb
- config/sidekiq.yml.example
In sidekiq.yml.example, we need to add a queue for archiving and metrics
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context – why has this been changed/fixed.
References: CV2-4221
- Etc.
> Add queue for archiving and metrics

- test/integration/parsers/kwai_test.rb
Fix Kwai failing test and make it more resilient.
`rails test test/integration/parsers/kwai_test.rb:4`
- Etc.
> Fix Kwai failing test

- app/models/parser/youtube_item.rb
- test/models/parser/youtube_item_test.rb
Add new URL schemes for the YouTube Parser:
1. Support for different subdomains: Handles `www.`, `m.` (mobile), and no subdomain variations.
2. Domain variations: Supports both `youtube.com`, `youtu.be`, and `youtube-nocookie.com`.
3. Path variations: Supports paths like `/watch`, `/embed/`, `/v/`, `/e/`, `/shorts/`, `/live/`, `/playlist`, etc.
4. Query parameters: Allows for multiple query parameters like feature, list, index, etc.
5. Timestamps: Supports timestamps like `#t=1m30s`, `#t=10s`, or `t=60s`.
6. Special cases: Includes cases like `oembed?url=`, `attribution_link?a=`, and others.
References: CV2-5245
Tested that the URLs below are successfully matched:
<details>
<summary>Valid URLs</summary>
http://www.youtube.com/watch?v=-wtIMTCHWuI
http://youtube.com/watch?v=-wtIMTCHWuI …
> Add more URL schemes for YouTube

- .gitlab-ci.yml
This updates the version pin for setuptools for this python based Docker image.
This fix was verified in check-api which is using the same Python docker image for deployment.
> Pin version for this distribution.

- Dockerfile
- production/Dockerfile
Upgrade Pender's ruby version to version, `3.3.3`
References: CV2-5548
Confirmed that all tests work and builds are successful
> Upgrade ruby to version 3.3.3

- test/integration/parser/page_item_test.rb
Fix this broken test.
This page doesn't seem to have this author's twitter and username anymore.
References: TICKET-ID, TICKET-ID, …
- Etc.
> Fix PageItemIntegrationTest#test_should_parse_url_scheme_https

- app/models/parser/facebook_item.rb
- test/models/parser/facebook_item_test.rb
We noticed that some facebook items weren't being parsed by the facebook parser, but by page. The issue was the url was being changed during normalization/get_canonical, and the final url we got wasn't being matched to the parser.
The fix was to add a new regex pattern.
References: CV2-6174
1. I added the original url and the final one to the test `"matches known URL patterns, and returns instance on success"`. 
2. Tested manually through swagger: After making a request I made sure provider was `facebook`, type `item` and the apify response was present.
I tested with these two urls:
- original url: https://www.facebook.com/maspmuseu/posts/pfbid0HqdatRwvYR9BFXsGDG1A9Q2xG952LoB6HACbenPPSMWy8SWw66Q26MnEovkQPEt3l 
- final url: https://web.facebook.com/maspmuseu/posts/na-obra-paisagem-114-a-art …
> 6174 – Match facebook item to facebook parser

- .gitlab-ci.yml
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context – why has this been changed/fixed.
References: https://meedan.atlassian.net/browse/CV2-6218
This was tested with a branch deployment to QA.
Only version pins should be changed in this update.
> Set version pins for Python 3.7.7 docker image.

- .github/workflows/ci-deploy-env.yml
Upgrading one more instance of `actions/cache` that was missing.
References: No Jira ticket associated.
CI should pass now.
> Upgrading actions/cache in one more workflow file

- app/models/concerns/provider_youtube.rb
- test/models/parser/youtube_item_test.rb
This causes issues with similarity matching.
References: CV2-6267
- Etc.
> do not set title/description to "Deleted video"/ "This video is unavailable"

- .github/workflows/ci-deploy-env.yml
Update the workflow dispatch from pender to sysops repositories. 
References: CV2-4921, CV2-6275
- Etc.
> 6275 – Update CI deploy action

- app/models/concerns/provider_facebook.rb
- test/data/facebook-item-apify-response.json
- test/data/facebook-video-apify-response.json
- test/models/parser/facebook_item_test.rb
When we parsed videos, we got an answer from Apify, but didn't use it. Because the keys in the Apify response are different between videos and posts. We were only looking for the posts' keys. I think we didn't notice this, because we were able to use the data we could parse from the HTML. 
This updates the Apify provider to also look for the video related keys. What a media created from a watch url looks like now:
I also took the opportunity to refactor a bit. I thought there was a bit of duplication.
References: CV2-6357
I added a new test: `bin/rails test test/models/parser/facebook_item_test.rb:98` 
For this test I added a new response from Apify so we could test this, and moved both the new one and the old Apify response to the data folder, so that the test file is cleaner.
I also ran …
> 6357 – Deal with video item response from Apify

- Gemfile
- Gemfile.lock
- test/lib/cookie_loader_test.rb
- test/lib/tracing_service_test.rb
- test/models/parser/dropbox_test.rb
After we upgraded our Ruby and Rails version, the old Minitest version we had wasn't working so well. One of the issues we ran into was being unable to run tests by specifying the line (e.g.: `bin/rails test test/models/parser/dropbox_test.rb:66`). In order to fix that, we had to upgrade Minitest.
- `MiniTest` constant was changed to `Minitest`, so I searched for occurrences in our code and changed them,
- the old Mocha version we had was incompatible with Minitest v5.19 and later (https://github.com/freerange/mocha/issues/614), so I updated that as well,
- there was a change in how to use `Minitest.mock` that caused 4 of our tests to fail, I updated them accordingly (https://github.com/minitest/minitest/issues/912)
References: CV2-6264
Please describe the tests that you ran to verify …
> update minitest and mocha

- .github/workflows/ci-deploy-env.yml
- .github/workflows/ci-test-pr.yml
- README.md
Since we renamed the `develop` branch to be called `main`, I updated mentions to `develop` to be to `main`.
References: CV2-6379
- Etc.
> 6379 – Update actions to use main

- db/schema.rb
I'm not sure when this file was updated, but it should probably be tracked in git? 
References: TICKET-ID, TICKET-ID, …
- Etc.
> update schema.rb to match the latest migration

- app/models/concerns/media_apify_item.rb
Send the Apify response to Sentry, so have more context into each Apify error.
References: CV2-5814
- Etc.
> 5814 – Send more information with the ApifyError

- Dockerfile
From the docs it seems we should wrap the value in quotes: https://docs.docker.com/reference/dockerfile/#label.
References: none
- Etc.
> Add quotes to label value in Dockerfile

- test/test_helper.rb
I noticed that I was running into issues when testing locally because there was cache present, when we didn't expect it to be. The test was failing to actually test the parser we were trying to test because of this. So this:
- **Makes sure the cache test directory is cleaned before tests start**
- **Make sure cache is clean before each individual test**
- Etc.
> Fix test caching issue
