meedan/pender

app/models/concerns/media_page_item.rb
test/models/media_test.rb

Also:
When some metatag returns nil or blank it doesn't overwrite the key on
data

Ticket #5048: Added more tests for parsing metatags from html pages

---

app/models/concerns/media_facebook_item.rb
test/models/media_test.rb

Also avoid error when page doesn't have a permalink

Ticket #5317: Normalize canonical url taken from facebook object

---

app/models/concerns/media_facebook_item.rb
app/models/concerns/media_facebook_profile.rb
app/models/media.rb
test/models/media_test.rb

Try to identify if the url pattern matches facebook profile before
comparing with facebook item
Facebook urls that are not identified by a specific pattern will be identified as
facebook item

Ticket #5545: Changes order of identification of Facebook pattern

---

app/models/concerns/media_page_item.rb
test/models/media_test.rb

Twitter recommends the metatag with the format:
<meta *name*="twitter:creator" content="<something>"/>
But on flickr, for example, the metatag is like:
<meta *property*="twitter:creator" content="<something>" />
Now Pender will support both metatags

Ticket #5757: Fix how to get twitter metatags from pages

---

app/models/concerns/media_facebook_item.rb
test/models/media_test.rb

Also: avoid FB url's with `album.php` because they can't be used as embed

Ticket #5940: Suport Facebook links with `pg` and `album.php`

---

app/models/concerns/media_facebook_profile.rb

The field `bio` is deprecated for versions v2.8 and higher and the
content will be available on `about` field

Ticket #6069: Removed `bio` field from list of facebook user_fields

---

app/controllers/api/v1/medias_controller.rb
app/models/media.rb
test/controllers/medias_controller_test.rb

Also avoid calling `as_json` twice

Ticket #6146: Handle error when call oembed format

---

app/controllers/api/v1/medias_controller.rb
app/models/concerns/media_facebook_item.rb
app/models/media.rb
test/controllers/medias_controller_test.rb

With this fix, Pender will recognize urls like the example below as the
same on controller and avoid parsing again:
"https://facebook.com/caiosba" and "https://facebook.com/caiosba/"

Ticket #6237: Normalize url before trying to find the media cache

---

app/models/concerns/media_facebook_profile.rb
app/models/concerns/media_page_item.rb
app/models/media.rb
test/models/media_test.rb

The redirection `https` to `http` is allowed only when the request
doesn't have credentials for `http_basic_authentication` header
Also:
- search for `author_name` in more meta tags
- decode url when trying to parse FB username;

Ticket #6173: Add support to pages that redirect from https to http

---

app/models/concerns/media_oembed_item.rb
test/models/media_test.rb

On media page the default Pender html will be displayed

Ticket #6305: Return blank `html` on oembed when script src is not https

---

app/models/concerns/media_facebook_profile.rb

Other errors with Facebook profile urls will not raise Errbit error, but
will be on log

Ticket #6617: Raise errbit error only when FB token is expired

---

app/controllers/api/v1/medias_controller.rb
test/controllers/medias_controller_test.rb
test/models/media_test.rb

This kind of url is not a valid url

Ticket #6827: Avoid parsing url with format `http://user@provider`

---

app/models/concerns/media_html_preprocessor.rb
app/models/concerns/media_screenshot_archiver.rb
test/models/media_test.rb

Also avoid parsing sharethefacts urls that are not replaced by JS

Ticket #7198: Fix regex to get the sharethefacts id

---

app/models/concerns/media_youtube_item.rb
app/models/concerns/media_youtube_profile.rb
test/models/youtube_test.rb

Ǵet all data from Youtube in one request
Set the data `picture` following the order of thumbnails size: maxres => standard => high => medium => default

Ticket #7298: Get all thumbnails available from Youtube API

---

app/models/concerns/media_facebook_item.rb
test/models/facebook_item_test.rb

Ticket #7519: Get image from original post when is a shared FB post

---

app/models/concerns/media_facebook_item.rb
test/models/facebook_item_test.rb

Also:
Facebook changed and URLs like (1) and (2) are not redirected to the same page
and don't have the same canonical URL, so the test for them was removed
1- 'https://www.facebook.com/democrats/posts/10154268929856943/'
2- 'https://www.facebook.com/democrats/videos/10154268929856943/'

Fix Facebook tests

---

app/models/concerns/media_oembed.rb
app/models/concerns/media_oembed_item.rb
test/controllers/medias_controller_test.rb
test/models/facebook_item_test.rb
test/models/facebook_profile_test.rb
test/models/media_test.rb
test/models/youtube_test.rb

Also:
- Includes error key and message on `raw[:oembed]` when there's an error
- Add new key `oembed` to store the page `oembed` (if available) or the default oembed

Ticket #7617: Store the `oembed` data on `raw` as it comes from parsing

---

app/models/concerns/media_archiver.rb
app/models/concerns/media_perma_cc_archiver.rb
test/controllers/base_api_controller_test.rb
test/models/archiver_test.rb
test/test_helper.rb

Also avoid crash when API key have `nil` on application_settings

Ticket #7776: Disable Perma.cc archiver if config is not present

---

app/models/concerns/media_facebook_engagement_metrics.rb
test/models/facebook_profile_test.rb
test/models/media_test.rb

Also add the URL on Airbrake params

Ticket #8080: Get metrics from non-ascii URLs

---

.gitlab-ci.yml

This change adds support for environment configuration using the SSM parameter store for Pender and Pender background tasks deployed via GitLab-CI.

Fix gitlab ci deploy

---

.gitlab-ci.yml

This is one of a couple pull requests to normalize SSM parameter prefixes to lowercase. This better matches the format in use in Terraform and AWS.
Live and QA configuration has been updated as per the [SSM import branch of configurator](https://github.com/meedan/configurator/tree/ssm-migration/ssm_import).
This change can be merged when convenient; the existing configuration lives along side the new format to ensure a seamless migration.  The deprecated settings can be deleted once the migration is complete. (This will be a separate sysops ticket.)

Normalize SSM parameter names to lower case.

---

.gitlab-ci.yml

This change updates the boto3 and botocore version pins in the GitLab-CI deploy to avoid an incompatibility in the ecs-deploy utility. Fixes deployment errors in develop.

Fix botocore version pins to avoid incompatibility in ecs-deploy utility

---

.gitlab-ci.yml

During a review of SSM parameters in Live, it was observed that the pender service is still referencing some long deprecated parameters.
This change updates the ECS deploy commands to use exclusive secrets and environment parameters. Once deployed, the pender tasks will no longer reference deprecated parameters like the `s3_*` values and the UpperCase `/Live/` prefix.

Remove deprecated params

---

app/models/concerns/media_kwai_item.rb
app/models/media.rb
test/models/kwai_test.rb

We didn't have a specific parser for Kwai URLs, so it was falling back to oEmbed information and metatags, but it means that the title and description are the same for all shared URLs from Kwai. This change add a specific parser that is able to extract the user who shared the video and the user who created the video, and use that information to fill some of the Pender data fields.
Reference: CHECK-1806.

Better URL parsing for Kwai URLs.

---

app/helpers/medias_helper.rb
test/models/tiktok_test.rb

When parsing some TikTok URLs, we get a timeout error. Trying to use a proxy to see if it fixes the issue.
Reference: CHECK-1320.

Use proxy when parsing TikTok URLs

---

app/helpers/medias_helper.rb
app/models/concerns/media_crowdtangle_item.rb
app/models/concerns/media_instagram_item.rb
test/models/instagram_test.rb

Use Crowdtangle to parse Instagram links, like we do with Facebook links.
This change also includes a performance improvement that caches Crowdtangle responses.
Reference: CHECK-1201.

Parse Instagram links

---

app/models/concerns/media_instagram_item.rb
app/models/concerns/media_tiktok_item.rb
config/cookies.txt.example
test/models/instagram_test.rb

Cookies must be set in `config/cookies.txt`.
Fixes CHECK-1843 and CHECK-1201.

Use cookies to parse Instagram and TikTok links

---

app/models/concerns/media_crowdtangle_item.rb
app/models/concerns/media_instagram_item.rb
test/helpers/medias_test.rb
test/models/instagram_test.rb

Now the Instagram parser gets more fields, like author URL, picture and published date.
Also, removing dependency on Crowdtandle - the GraphQL endpoint contains all the data we need.
Reference: CHECK-1201.

Fixing Instagram parser

---

app/models/concerns/media_twitter_item.rb
app/models/concerns/media_twitter_profile.rb
test/models/media_test.rb
test/models/twitter_test.rb

* Surface Twitter API error to the root of the returned "data" structure
* Looks like Twitter doesn't return a canonical URL anymore

Fixing some automated tests related to Twitter parser

---

test/helpers/medias_test.rb
test/models/media_test.rb

With the Meedan site redesign, we seem to no longer have social tags
in the header. As a result, the tests in Pender we use to validate
some parsing behavior (on author and opengraph metadata) is failing.
To address this for now, I went ahead and updated the tests to read
from other URLs that have the data we're looking for. We should
consider doing two things longer term:
1. Add social metadata to Meedan.com, and possibly add the Meedan.com
tests back in here or elsewhere, since they seem useful to tell us
about our own site even if it wasn't the specific intention of these
tests
2. Consider testing against fixtures instead of live websites

Replace tests against Meedan website

---

app/models/concerns/media_instagram_item.rb

Running into this is another sign we are running into problems
with the Instagram API, so we want to send to Errbit.
CHECK-1201

Add privacy check URL to list of problematic Instagram URLs

---

test/test_helper.rb

We don't think we need to retry so much since we no longer have
a flaky Facebook parser, and retrying so many times increases the
amount of time it takes to get a truly failling test run.

Reduce number of retries in test

---

app/models/concerns/media_facebook_engagement_metrics.rb
app/models/concerns/media_metrics.rb
app/models/media.rb
app/workers/metrics_worker.rb
test/controllers/medias_controller_test.rb
test/models/archiver_test.rb
test/models/metrics_test.rb
test/workers/archiver_worker_test.rb

We were seeing a race condition where the metrics update
returned before the intiial request created the record on the
Check API-side. Since Check API doesn't currently return a
different status if the Media with URL isn't present in the
database, we want to just delay the initial call to try to
ensure that the record is created before we try to update it.

Delay initial metrics request

---

app/models/concerns/media_facebook_engagement_metrics.rb
app/models/media.rb
test/models/metrics_test.rb

Before we were silently failing when a webhook URL was not
configured for an API key, which we expect to be set in
real environments. This gives us an indication, and also adds
some other logging around the metrics background job to
help with debugging.

Add logging for debugging metrics job

---

app/models/concerns/provider_facebook.rb
app/models/parser/facebook_item.rb
app/models/parser/facebook_profile.rb
test/models/parser/facebook_item_test.rb
test/models/parser/facebook_profile_test.rb

Previously we were only stripping if it came through a specific method, but there are multiple ways we might set title. This moves stripping to a cleanup step at the end of each provider.

Always strip " | Facebook" from Facebook titles

---

.travis.yml
README.md
config/config.yml.example
config/initializers/load_cookies.rb
lib/aws_s3_client.rb
lib/cookie_loader.rb
lib/pender_store.rb
test/lib/cookie_loader_test.rb
test/models/media_test.rb

We're moving away from using Configurator, which means that we need a way to include cookies that aligns with how we now treat other secrets. This commit moves toward us setting an S3 file path in `config.yml`, which would point to a file in an S3 bucket that contains the required cookies. This request will be authenticated with the credentials we already use for storage-related S3 items.
The config setting is `cookies_file_path`, and can point to the local filesystem (for development and, if needed, test) or to a file on S3.
If no `cookies_file_path` is provided in the config, it defaults to what we previously used: `config/cookies.txt`.
Also:
* Removes cookies.txt from the Travis CI file (since we won't have it available). Removes dependencies on that file being present locally in test, …

Allow setting Pender cookies from file on S3

---

app/controllers/api/v1/medias_controller.rb
app/helpers/medias_helper.rb
app/models/media.rb
lib/pender_store.rb
test/controllers/medias_controller_test.rb
test/helpers/medias_test.rb
test/models/media_test.rb
test/models/parser/twitter_item_test.rb

Also addresses unrelated failing test caused by change on Hacktober page

Check 2457 do not cache failed pender responses

---

Gemfile
Gemfile.lock
README.md
app/models/metrics.rb
config/config.yml.example
config/initializers/load_cookies.rb
config/initializers/open_telemetry.rb
lib/pender_open_telemetry_config.rb
test/lib/pender_open_telemetry_test.rb
test/test_helper.rb

Confirmed in test and development, including dev reporting externally to Honeycomb.
Caio and Dani, would love either of you to look at this if you have the time! Particularly interested in thoughts on how we set and override Open Telemetry config values, since it's kind of complex.
**Context:**
We recently enabled reporting to Honeycomb via Open Telemetry; however,
we were avoiding configuring OT with the instrumentation gems in dev and
test to reduce noise. Once deployed, we found that we were getting a
stack level too deep error when the Twitter gem made requests using the
underlying http gem, which wasn't happening in development or test
since it was caused by an interaction between the Open Telemetry and
Airbrake gems.
More on the specific problem here: …

Fix stack level too deep bug caused by Airbrake & Open Telemetry

---

app/models/concerns/provider_instagram.rb
app/models/parser/base.rb
app/models/parser/instagram_item.rb
app/models/parser/tiktok_profile.rb
test/models/parser/instagram_item_test.rb
test/models/parser/instagram_profile_test.rb
test/models/parser/tiktok_profile_test.rb

The URL was slightly incorrect before, and we want to be able to set an alert on any error that would require us rotating the cookies.

Make sure we detect the Instagram challenge page as an error

---

config/initializers/open_telemetry.rb
lib/pender_open_telemetry_test_config.rb
test/lib/pender_open_telemetry_test.rb
test/lib/pender_open_telemetry_test_config_test.rb
test/test_helper.rb

Previously we were just adding a span_processor, which the documentation suggests. However, we want to use tests to help identify any bugs resulting from the enabled instrumentation, and running OpenTelemetry.configure overwrites the existing configuration at app start, meaning that no instrumentation was enabled when tests were running. This means that if bugs were introduced, we still wouldn't see them in a test environment.
Instead, this enables all instrumentation we currently use in dev/deployed environments, and creates a helper to let us selectively turn on recording for use in test environments. By default recording is disabled, which means that no spans will persist in memory.

Use same Otel instrumentaiton in test as in other envs

---

app/models/parser/instagram_item.rb
test/models/parser/instagram_item_test.rb

We were accidentally overwriting everything in the raw key when setting the api data, which was causing problems when we tried setting fallback values from the metatag data.
Also did a visual pass to make sure that we weren't doing this anywhere else obvious in other parsers.

Don't overwrite raw metatags with raw API data in IG item parser

---

app/models/parser/instagram_item.rb
test/models/parser/instagram_item_test.rb

Previously newlines were breaking our regex for detecting Instagram text. Adding the m modifier to the regex still matches if they are present.

Add support for newlines in Instagram fallback title & desc

---

app/models/media.rb
test/models/media_test.rb
test/models/parser/facebook_item_test.rb

Previously we were only running canonical URLs through normalization if they were not found in the HTML. This lead to an edge case where we were returning different URLs for effectively the same item - one if it was parsed in the HMTL (eg with a trailing slash) and a different one if it used the passed URL (which was then run through Postrank::URI.normalize, which stripped trailing /, among other things).
This is a pretty big change since it will mean that many duplicates may be created in Check API (since it asks Pender for a canonical URL when looking up existing Links, and that will change).

Normalize all media URLs

---

app/helpers/medias_helper.rb
app/models/concerns/provider_instagram.rb
app/models/concerns/request_helper.rb
app/models/media.rb
app/models/oembed_item.rb
test/models/media_test.rb
test/models/oembed_item_test.rb
test/models/parser/facebook_item_test.rb
test/models/parser/youtube_item_test.rb

Returns to how we were normalizing URLs before, since it is both deterministic
and gets us the most successful results. This also adds in a few refactors that
were done during the bug exploration: 1) expanding the redirect codes we look
for to include ones we see less frequently (308 for The Atlantic, for example),
and 2) trying to reduce dependencies and alteration of internal state where
possible, instead preferring explicit passing and return of dependencies for
internal helper functions.

Revert to previous URL normalization patterns

---

README.md
config/config.yml.example
config/initializers/zz_open_telemetry.rb
lib/pender_open_telemetry_config.rb
lib/pender_open_telemetry_test_config.rb
test/lib/pender_open_telemetry_config_test.rb
test/lib/pender_open_telemetry_test_config_test.rb

To start out, we want to send all information to Honeycomb. But, depending on the volume of traces generated, we may want to reduce the amount of traces that we send. This commit enables that: sending all data by default, and setting a sampler with sample rate in the case that we want to limit.
To use, we would need to set the following in config.yml:
* `otel_traces_sampler` - should be a Open Telemetry supported value, like traceidratio
* `otel_custom_sampling_rate` - this should be a number, ideally an integer, representing the amount we want to sample. It will be set as the relevant config for Open Telemetry (e.g. if 5 if set, then SampleRate=5 will be sent as an attribute, and OTEL_TRACES_SAMPLER_ARG will be set in environment to 0.2
This commit also consolidates instrumentation into …

Add ability to sample traces in Open Telemetry

---

lib/pender_open_telemetry_config.rb
test/lib/pender_open_telemetry_config_test.rb

Since we load from yml file, we can easily pass nil in for these values. This sets defaults assuming that sometimes we will be passed nil, but we always want a hash.
It's possible we might want more guard rails in future (like, erroring if the passed config doesn't have the shape we want, or passing things in individually, etc) but this seems sufficient to fix current issues with deployment.

Set defaults for unset Open Telemetry config

---

app/controllers/application_controller.rb
lib/tracing_service.rb
test/controllers/base_api_controller_test.rb
test/lib/tracing_service_test.rb

Will help us troubleshoot in traces, and uses the same approach as is currently in Check API.

Send ApiKey id to Honeycomb

---

app/controllers/api/v1/base_api_controller.rb
app/controllers/application_controller.rb
test/models/archiver_test.rb

I added this attribute in a prior commit, but it was being sent before the ApiKey was set in a child controller. This changes the send logic so that we only send after we have an ApiKey.

Make sure we have an ApiKey before we try to send to Honeycomb

---

README.md
test/models/archiver_test.rb

Previously we weren't calling up to the test_helper teardown, which meant that the resetting of enabled archivers wasn't happening consistently. This commit calls super to make sure we get both teardowns, and ensures that we reset the values of the ENABLED_ARCHIVERS constant to the start of the test when they change mid-test.

Fix flakiness in archiver tests

---

app/models/concerns/media_archive_org_archiver.rb
app/models/concerns/media_archiver.rb
app/models/concerns/media_perma_cc_archiver.rb
app/models/media.rb
app/models/metrics.rb
test/controllers/medias_controller_test.rb
test/models/archiver_test.rb
test/models/media_test.rb
test/models/metrics_test.rb
test/workers/archiver_worker_test.rb

This PR does a few things:
1. Adds a delay before kicking off the archiving jobs, to give Check API a headstart to start creating the link, project media, and annotation that will be needed to associate the archival information
2. Begins raising exception when the webhook notification to Check API returns an unsuccessful response, which Sidekiq will then retry.
3. Uses WebMock to stub external requests to the endpoint in tests, and removes dependency on the external webhook endpoint on Caio's site (partly because it was returning 301, which is considered unsuccessful)
**Given that we should always expect the Check webhook to be working when we send a webhook notification from Pender, I think always retrying when the endpoint errors makes sense regardless of what that error returned from …

Re-queue webhook notification job when webhook returns an errored response

---

config/initializers/airbrake.rb

Previously if a non-archiving job was hitting the max retries and the Sidekiq config for max retries was unset then that error reporting to Errbit woudl raise its own exception because it was trying to compare an integer to nil.
Trying to determine mathematically if we've hit the max number of retries in the filter is difficult, and we don't yet have access to Sidekiq variables since we're in the initializer. Ideally we would raise a final error by configuring sidekiq_retries_exhausted in each of the workers that handle it, but for now we can just hardcode the max number of retries to the max number of retries in Sidekiq and call it a day.

Hardcode Sidekiq max retry when deciding to send to Errbit

---

app/models/metrics.rb
lib/tracing_service.rb
test/lib/tracing_service_test.rb
test/models/metrics_test.rb

Try to quiet Errbit a bit, since we get a ton of non-actionable errors. They're useful for keeping track of what's happening, but sending to an exception reporting service seems like a lot.

Send metrics errors to Honeycomb, and silence retryable ones

---

lib/pender_open_telemetry_config.rb

Redis accounts for most of our events in Honeycomb, which we're often going over, but we don't find it very useful. This removes the instrumentation so that we no longer track that information.

Stop sending Redis information to Honeycomb

---

app/controllers/api/v1/medias_controller.rb
app/helpers/medias_helper.rb
app/models/concerns/media_archive_org_archiver.rb
app/models/concerns/media_archiver.rb
app/models/concerns/media_perma_cc_archiver.rb
app/models/concerns/media_video_archiver.rb
app/models/media.rb
app/models/metrics.rb
test/controllers/medias_controller_test.rb
test/models/archiver_test.rb
test/models/media_test.rb
test/models/metrics_test.rb
test/models/parser/page_item_test.rb

Previously we were using the original URL to control cache. This causes
a problem because we use the normalized URL to communicate with Check API,
causing a problem because there would often not be a cache present for
the same link that was previously submitted if the normalized verison was
different than the original link.
This takes the approach of using normalized URLs for caching, so we have a
single source of truth that is compatible with the way that Check API stores
URLs from Pender.
This also sends the normalized URL to the archiving service, instead of
the original URL. Using the original URL for archiving because the archiving
service wasn't matching the Link saved to Check API, which was stripped previously by Pender. This commit brings in line
the URL parsing behavior so that …

Use the normalized URL when accessing cache, and send to archivers

---

app/models/media.rb
app/models/metrics.rb
app/workers/metrics_worker.rb
test/models/archiver_test.rb
test/models/metrics_test.rb
test/workers/archiver_worker_test.rb

Previously, in some cases we were exponentially creating new Metrics updates for URLs beacuse we queued the next update inside the existing background job, and relied on a passed variable to dictate when to stop scheduling jobs (that on error would not always be set).
This instead schedules all of our updates at the start (for ten days, the previous setting) and caps the amount of retries up to one day (according to the Sidekiq documentation for back-off timing). This means there will be a max of 130 metrics fetches per link. We could reduce this if we wanted (either by turning off retries entirely, or - maybe better - only retrying the first, since it's presumably most important). Curious for your thoughts @caiosba.
In theory we could stop passing count / update_number, but this would …

Prevent exponential creation of metrics jobs on failure

---

config/initializers/airbrake.rb

This constant was being redefined each time Airbrake hit the filter, which wasn't intended and was causing warnings in our logs. This moves the constant definition outside of the function scope.

Don't redefine constant

---

app/models/concerns/provider_facebook.rb
app/models/parser/base.rb
app/models/parser/facebook_item.rb
test/models/parser/facebook_item_test.rb

Begins sending some additional information about parsers to Honeycomb to help with debugging.
May want to consider having parsing as its own span, but think this works for now.
Also corrects some whitespace in the files I touched.

Send parser information to Honeycomb

---

app/models/media.rb
app/models/parser/telegram_item.rb
test/data/telegram-item.html
test/models/parser/telegram_test.rb

Previously Telegram links were being parsed by the PageItem parser, which used the non-unique title as our title, which is used for similarity matching. Because Telegram sets the title of the page to the channel that published it, this meant that items were being marked as similar just because they were published by the same channel - not necessarily the same topic.
To address this, this commit creates a TelegramItem parser that simplifies the fetching logic (mostly the same as what PageItem did), and sets the title as the URL since there is no other unique identifier provided (eg, no post title).
Telegram profiles seemed to parse as I'd expect, so I continued to let those fall back to PageItem as they do now.
**Before / currently on QA**
**After**
CV2-2612

Create TelegramItem parser and set title to URL

---

Dockerfile
Gemfile
Gemfile.lock
config/database.yml.example
docker-compose.yml
production/Dockerfile
test/models/media_test.rb

Previously we were using sqlite for development and test environments while our deployed environments used postgres. This caused an issue during the Rails upgrade where our Postgres version was out of date but never caught locally or in CI because of the difference in configuration. This commit has us use postgres as the local database, removes references to sqlite, and updates postgres to be compatible with the 6.1 version of ActiveRecord.
CV2-2668

Use postgres in development and test, instead of sqlite

---

config/application.rb

After upgrading to Rails 6.1 and Ruby 3.0, our deploys began failing due to a missing storage.yml. storage.yml is needed to configure ActiveStorage, which we don't currently use. Not totally sure why it's showing up now and not when we upgraded to Rails 5.2.
To sidestep this, configure ActiveStorage to use :local in all environments. We will want to change this in the future if we start using ActiveRecord.
CV2-2668

Fix failure to deploy due to missing storage.yml

---

config/application.rb
config/storage.yml

This is the default installed by Rails that we were missing due to upgrades. Although we're not using ActiveStorage, our deploys are erroring without this config file.
This also removes the declaration of local storage that had been previously added to try to get around this same error, since I think we don't need it and it will be confusing in the future.
CV2-2668

Add basic storage.yml to fix deploys, and remove unused config

---

app/views/layouts/application.html.erb

By default, Facebook embeds have a fixed width of 552px. On Check Web, the embed container is wider than that, so the embeds are displayed aligned to the left. This PR makes sure that the Facebook embeds are displayed with full width.
Fixes CV2-2857.

Full width Facebook embeds

---

app/views/layouts/application.html.erb

There is a hard-coded width of 550px which we can't change, but we can increase the current embed width from 250px to maximum 550px, make it responsive and centered. This is what this commit adds.
Fixes CV2-2857.

Wider display for Twitter embeds.

---

app/models/concerns/provider_instagram.rb
test/models/parser/instagram_profile_test.rb

Instagram began redirecting to /login when requiring authentication for certain pages, so we need to add it to the list of URLs that we cannot parse.
CV2-2901

Add new Instagram login URL

---

lib/pender_sentry.rb

Previously we were using tags, which isn't quite right. They are searchable but only support primitives as a result, which didn't make sense for the data we wanted to send.
This instead moves toward using context, which is more readable in the Sentry interface and allows us to send complex data like we were before. More of a drop-in replacement for how we were using Errbit.
For this approach, we just need to watch the size of the payload. We could set additional contexts with unique names in the future. More on that here: https://develop.sentry.dev/sdk/event-payloads/contexts/
CV2-2897

Use context to send additional metadata to Sentry

---

app/models/metrics.rb
config/initializers/03_sidekiq.rb
test/models/parser/instagram_profile_test.rb

- Failed jobs were sending job information instead of wrapped exception information
- RequestFailedException showed "<Class-asldkfjas>::RequestFailedException" because the custom exception was defined within the self block instead of within the module block.
CV2-2897

Small fixes: Improve error reporting to Sentry

---

app/controllers/api/v1/base_api_controller.rb
lib/pender_sentry.rb
test/controllers/base_api_controller_test.rb
test/lib/pender_sentry_test.rb

This will add an API Key ID, similar to what we use in Honeycomb, to error information sent to Sentry.
This uses the same interface as Check API's Sentry class, but sets the user_id as the API key since that is our closest proxy for a user in this application. Check API uses the actual User ID for this.
CV2-2897

Add ApiKey as user information in Sentry

---

app/models/concerns/media_oembed.rb
app/models/media.rb
app/models/parser/file_item.rb
test/models/parser/file_item_test.rb

Currently we're causing an error when a user submits a file URL to Pender, either via the Check web interface or API. This means that partners can't submit links pointing to files.
While we want to eventually detect filetype using a HEAD request to the URL before fetching the file itself, this is a quick and easy way for us to do a best guess at most file types we would expect using the current flow - making a get request, then passing it off to a parser that matches the URL structure.
In order to prevent erroring on the Check API side, I also had to prevent the oembed from returning the file data. This invovled what I hope is a temporary carveout for file parsers, and telling them to use the default Oembed.
The result of all of this is that users can submit a link to a file and just see …

Implement a FileItem parser

---

config/environments/production.rb

At some point in past we set this to :info, but it obscures any warning and other output that would help us understand what's going on in our logs for deployed environments. So, let's set it back.

Set log level to debug in deployed environments

---

config/environments/production.rb
production/bin/create_configs.sh

Previously we were pulling this value from SSM, which sometimes was confusing. Now we will be reading from the committed production.rb in deployed environments.
There was nothing specific to the environment configured in the file—just what was already committed, or an unintentional variation of it—, so we don't need to add any new SSM variables.
CV2-3054

Update production.rb to actually be used in production

---

app/helpers/medias_helper.rb

Updated URI open to be more secure
From CodeQL:
If Kernel.open is given a file name that starts with a | character, it will execute the remaining string as a shell command. If a malicious user can control the file name, they can execute arbitrary code. The same vulnerability applies to IO.read, IO.write, IO.binread, IO.binwrite, IO.foreach, IO.readlines and URI.open.
TLDR:
If you pass the url directly to URI it will error if it's anything other than an URI. You can pass more 'things' to open, which makes it more susceptible to malicious action.

CV2-3030: Replace URI.open with URI().open in Pender

---

app/controllers/application_controller.rb

We want to remove the CodeQL warning about CSRF.
From the docs:
APIs may want to disable this behavior since they are typically designed to be state-less: that is, the request API client handles the session instead of Rails. One way to achieve this is to use the :null_session strategy instead, which allows unverified requests to be handled, but with an empty session
source:
https://api.rubyonrails.org/classes/ActionController/RequestForgeryProtection.html#method-i-verify_authenticity_token
As Caio requested, I ran an integration test, just to double check it didn't break anything, and that passed 🎉

CV2-3119: protection weakened or disabled warning

---

app/models/parser/facebook_item/ids_grabber.rb

Here we are trying to grab an `id` from facebook (post, album, etc.) We do that by matching patterns. When an url doesn't match our patterns, we run a fallback, `post_id_from_params(url)`, and try to get the id there. So we are looking for an `id` inside a key.
The problem here was we were looking for a key that didn't exist. If we get an url with a query for photos, like `https://www.facebook.com/search/photos?q=%E0%...`. It would look for the values from the key `"album_id"` in the `params` hash, but that key does not exist, the only key there is `"q"`, and that returns a query, not the id. 
So I updated the guard clause to check if the key exists in params.
References: cv2-3018
1. I ran the failing url. We stopped getting the error. We get `nil`, since there is no `id` to grab.
2. I …

3018 - update guard clause to avoid undefined method error

---

docker-compose.yml

Update to use Postgres 12, the scope of this was to make sure the application works well locally in development mode and that tests pass in Travis and in the Check Web integration tests.
References: cv2-3305, cv2-3308
To make sure the application works locally I ran the seeds file, and went through the interface to see if everything was created and working correctly. I also ran the integration tests on check-web (successfully), following the instructions in the confluence article (_How to run cross-application integration tests in CI on demand_). 
_Not sure if this is important to pay attention during code-review, but I think it's important to add_
- Since we are upgrading between major versions (11 to 12) we have to either migrate the data to a new volume or delete the old volume. …

3305 - Make sure pender works with PostgreSQL 12

---

app/models/parser/kwai_item.rb
test/models/parser/kwai_test.rb

This was surfaced through audit hour.
Inside the Kwai parser, we added a safe operator before `strip` in `get_kwai_text_from_tag`. We did so because that might be `nil` and we don't want it to return an error.
References: cv2-3019
I wasn't really able to fully test it. But this also seems pretty straight forward. Anyway, on the tests: 
- I wanted to test it against the url that caused the error on sentry, but the sentry issue is no longer there. I'm not sure why 🤔 I'm not sure how to reproduce this.
- We were skipping the kwai integration test, because it was broken. I ran it anyway and it seems to be working now. @hartsick should we go back to running this test?

3019 - add safe operator to avoid NoMethodError (kwai)

---

public/javascripts/embed.js

This was used in Bridge, isn't used more and was causing a cross-scripting warning: https://github.com/meedan/pender/security/code-scanning/15
References: cv2-3063
Ran the pender tests locally, but we have two failing tests: [should handle concurrency](https://github.com/meedan/pender/blob/3063-address-cross-site-scripting/test/integration/medias_integration_test.rb#L33) and [should generate the public archiving folder for videos](https://github.com/meedan/pender/blob/3063-address-cross-site-scripting/test/models/archiver_test.rb#L573). The second one seems unrelated, but I'm not sure about the first? It looks for a title but can't find it. I tried getting the html for that page, but it failed. However, on CI they all passed.
I also tested generating embeds (tiktok, twitter, telegram, …

3063 - address cross site scripting

---

docker-compose.yml

Upgraded Postgres to 13. Used the same image Devin used for Alegre.
References: 3465, 3464, 3468
Made some requests to pender manually, they all worked.

3465 - Make sure pender works with PostgreSQL 13

---

test/models/parser/facebook_item_test.rb

Sometimes facebook items are unavailable. Before we didn’t get any response in those cases, now we get a page letting us know the page is not available. With this we are now able to create an embed.
We want to keep this new behavior, so we only need to update the tests.
**What the embed looks like**
**On check**
References: 3571
Updated the failing tests.

3571 - Update unavailable facebook items tests

---

app/models/oembed_item.rb

We sometimes get an error when parsing the `oembed`: `TypeError: no implicit conversion of String into Integer`
This happens with similar specific urls, all weirdly named urls with `.top` domain. Those sites return '404' on their `response.body`, when we `JSON.parse` it, it returns an integer, which breaks things. 
This was fixed by returning early if the value is not a `Hash`.
References: 3386
Tested parsing some of the urls that were causing this error. (there are some examples on the ticket)

3386 - make sure oembed_json is a Hash

---

app/models/concerns/provider_facebook.rb
app/models/parser/facebook_item.rb
test/models/parser/facebook_item_test.rb

We don't want the title and description to be set to 'log in to facebook'.
The title should be the url and description should be an empty string.
We were having two issues:
1. the story link was being parsed by the page parser, so we updated the regex
2. the facebook parser was being redirected to a login page, which meant that the metadata we used for the title and description was 'log in...'. Now we check one final time and update the title if needed.
References: 3644
1. Added `assert Parser::FacebookItem.match?('https://m.facebook.com/story.php?story_fbid=pfbid0213Dz5MyduLTHpELPoRmop9E7zj3Ed163P7djxSWbkfvaMSBrjNYTY9BFx6h7i3zWl&id=100054495283578').is_a?(Parser::FacebookItem)` to  test "matches known URL patterns, and returns instance on success" (`rails test …

3644 - identify facebook login pages

---

app/models/concerns/provider_facebook.rb
app/models/parser/facebook_item.rb
test/models/parser/facebook_item_test.rb
test/models/parser/facebook_profile_test.rb

I had added a final check inside `facebook_item`, but realized that it would be better to update how the `provider_facebook` checks if a page is a login page, so we check only once instead of doing it twice.
This is a refactor of the work in this PR: [3644 - identify facebook login pages #381](https://github.com/meedan/pender/pull/381). 
References: 3644
`rails test test/models/parser/facebook_profile_test.rb:476`
I thought this was pretty straightforward, but found a small issue while working on this: 
We had a couple tests that wanted opposite things ("should add login required error and return empty html and description" / "should return html even when FB url is private"), they were both passing because we were sometimes failing to check for login pages.
The behavior we want is to …

3644 - facebok identify login pages refactor

---

app/models/parser/twitter_profile.rb
test/models/parser/twitter_profile_test.rb

Sometimes a profile url might come with a query, e.g: `https://twitter.com/username?ref_src=blah`. 
We need to make sure we are getting only the username to make the request to the twitter api endpoint. To do that I updated the regex inside `twiter_profile.rb`.
References: 3653
I added two new tests to the test "matches known URL patterns, and returns instance on success" (`rails test test/models/parser/twitter_profile_test.rb:41`).
I also added a new test that checks for this specific scenario "should parse tweet profile with a query on the url" (`rails test test/models/parser/twitter_profile_test.rb:203`).

3653 - extract username correctly when there is a query

---

test/models/parser/facebook_item_test.rb

For a while now we have one test from Kwai and one from Facebook that have been failing.
**Facebook**
I'm not too sure about everything here, but it seems:
- we have the `url` from the link, and inside the page we have the `canonical_url`
- we were getting the error because the `canonical_url` was being invoked, but was not stubbed. 
Stubbing it fixed that error
- we then get a new error, the `media.url` actually matches the `canonical_url` and not the `original_url`. 
So I updated our asserts as this seems to be the expected behavior.
**Kwai**
The test here seems to be working fine, but our parsing seems to be broken. 🥲 
We search the doc for `'.info .title'` and for `'.name'`, and both of those are returning `nil`.
I looked through the page, but haven't found a direct substitute for …

3716 – Fix Kwai & Facebook's failing tests

---

app/models/parser/kwai_item.rb
test/models/parser/kwai_test.rb

Our Kwai test has been failing for a while, since it had been flaky before we assumed it was just flaky again. However, it seems that the parsing is indeed broken: we search the doc for '.info .title' and for '.name', and both of those are returning nil.
We can get data from the jsonld script. Besides the `name`(we can get that from `creator name`), it doesn't return the same exact data as before. We can use `description` or `transcription` for `data['description']`. For `title` we don't have a good substitute, so we are just using the default fallback from `Media` (`url`).
We are leaving the old behavior and adding the data from the jsonld script as a fallback. Kwai has changed their HTML and changed it back again before. So we think it's worth keeping the old behavior, at least for now. …

3723 – Fix Kwai parser

---

app/models/parser/kwai_item.rb
test/models/parser/kwai_test.rb

We want to make sure kwai profiles are not being parsed by the item parser.
Until we add a profile item for kwai they will be parsed by page.
Notes:
- I added a regex for when we have a kwai-video host instead of only kwai.
- When we have the username in the url, we are getting it as a fallback.
References: 3723
test "matches known kwai URL patterns, and returns instance on success"
test "does not match kwai profile URL"
test "fallbacks to the username on the url when doc and json+ld are not present, if name is present in the url"

update regex in the kwai item

---

app/models/concerns/media_archiver.rb
config/initializers/03_sidekiq.rb
test/models/archiver_test.rb

We were notifying Sentry both through `Media.give_up` and through
configuration inside `03_sidekiq`. We are keeping only the one in `03_sidekiq.rb`.
It’s the most specific error and the right place.
In order to try to get more information, we are replacing
`Sentry.capture_exception(ex) by PenderSentry.notify(ex, { job: job })`
References: 3706, 3757, 3707
I tried writing a test to make sure teh Archiver isn't notifying Sentry anymore:
test "MediaArchiver should not notify Sentry when the worker hits the maximum number of retries"
`rails test test/models/archiver_test.rb:746`
I ran a bunch of tests to make sure the test is working, but I'm not sure about it: if it makes sense the way it's written, if it's even needed.

notify Sentry about RetryLimitHit only from sidekiq

---

config/initializers/02_sentry.rb
config/initializers/03_sidekiq.rb

We have been getting a lot of Metrics RetryLimitHit errors on Sentry. Unfortunately they don't tell us much. So we are trying to test ways of adding relevant Data to those Errors.
- added trying to send the `original_exception.cause` when we hit `RetryLimitHit`, hopefully this will give us some extra info
- added  `config.sidekiq.report_after_job_retries = true` which should make sure we are only getting the last retry( should only report the exception after all retries have failed). I think we are already only reporting the last retry, but added this to make sure. If we are reporting on more retries, this could help make it less noisy.
References: 3274
I wasn't able to test this one, we will have to see on Live if there is any new relevant information sent to Sentry.

3724 – Testing ways to better error handle RetryLimitHit (Metrics)

---

.travis.yml
test/test_helper.rb

When running locally we might not want the tests to retry, to do this
we would need to comment out the retry lines. We want to make this easier
on the developer
Converting the env variable to an integer because ENV[] on ruby returns a string
https://ruby-doc.org/core-3.0.0/ENV.html
References: 3718
Changed a test to make it fail. 
Ran tests locally without setting `TEST_RETRY_COUNT`, test failed and didn't retry.
Set the env var inside the container (`export TEST_RETRY_COUNT=5`) and ran the tests again, it retried 5 times.

3718 – Update how we retry tests

---

test/integration/parsers/kwai_test.rb
test/models/parser/kwai_test.rb

This is part of a larger project to improve our testing.
**Context**
We have two issues:
- We want to be able to choose when to run integration tests.
- We have too many integration tests.
To fix this we need to go through all the parsers and:
- Split the integration from the unit tests, we now have a folder for them (test > integration > parsers).
- Go through the unit tests and make sure they are not making live http requests.
- Go through the integration tests, see which one of those should be integration tests (keep those at 2, 3 tests at the most), and refactor the rest to be unit tests. (ideally we want one to test a successful request and one to test a failure)
**Notes on the Kwai tests**
This one was pretty straight forward:
- I moved integration test to it's own file
- Created a …

3634 – Refactor Kwai testing

---

.gitlab-ci.yml

This fix updates version pins for python packages awscli, boto3, botocore, and ecs-deploy to fix deployments.
I verified this deployment method in QA.

Remove version pins to fix deployments.

---

app/models/metrics.rb
config/initializers/03_sidekiq.rb

When we do `original_exception.cause` we are only getting the message in Sentry,
but if we do `original_exception.cause.inspect` we get the whole error.
References: 3796
- Set my local dev environment to notify Sentry 
- Set [retries](https://github.com/meedan/pender/blob/f773ef3f69cc7f7c72fb6d8ae04e38f3d09e6a17/app/workers/metrics_worker.rb#L6C3-L6C3) for the MetricsWorker to 1
- Raised `Pender::Exception::RetryLater, message: 'Original Error'` inside [get_metrics_from_facebook](https://github.com/meedan/pender/blob/f773ef3f69cc7f7c72fb6d8ae04e38f3d09e6a17/app/models/metrics.rb#L28)
- Ran requests as usual and watched the errors hit Sentry

3796 – Add more details to original exception for RetryLimitHit

---

app/models/media.rb
test/controllers/medias_controller_test.rb

The URL ID, used as a cache key, is calculated in runtime, at different times, when writing and when reading. This means that the cache is written to a key but read from another one. This is a pretty edge case, but this PR turns it safer and more consistent.
Reference: CV2-3749.
TDD. I added a test that first reproduced the issue. The test passed after the fix was implemented.

Fixing cache when ID changes

---

.gitlab-ci.yml

This pull request updates version pins for deployment dependencies including the six and urllib3 packages.
References: DEVOPS-502
I performed a deployment into QA with these versions to confirm the fix.

Update version pins for Python ecs deploy dependencies including six and urllib

---

app/models/concerns/provider_instagram.rb
app/models/parser/instagram_item.rb
test/models/parser/instagram_item_test.rb

One of our users saw a bug where some unrelated items were being matched. 
This happened because even though they linked to different urls their data was the same (the title for all of them were the instagram home url). They were also being parsed by page and not instagram item parser.
References: 3843
Added a live test (`test "should parse Instagram item when the final url is instagram.com"`) and a stubbed test (`test "should return url as title when redirected to instagram main page"`).

3843 – Unrelated instagram links from the same page being matched

---

app/models/concerns/media_archive_org_archiver.rb
test/models/archiver_test.rb

We want to send the closest snapshot as a fallback. So if our request errors we send both the error and the snapshot (if one is available)
References: 3707
We have a test that checks if `get_available_archive_org_snapshot` method returns the snapshot url. And we have another test to check if when the request fails it sets the closest snapshot as a fallback while also sending the error (`when archive.org fails to archive, it should add to data the available archive.org snapshot and the error`).

Archive.org should get the closest snapshot and send it as a fallback

---

app/models/concerns/media_perma_cc_archiver.rb
app/models/media.rb
test/models/archiver_test.rb

We realized we needed to update how we deal with when to archive, and that we should check for those conditions only in Media, `media_perma_cc_archiver` and `media_archive_org_archiver` should only worry about archiving to their respective site.
References: 3707
The tests are currently passing. For perma_cc: I updated one(`"should not try to archive on Perma.cc if already present in cache and no refresh is requested"`) and added another (`"should try to archive on Perma.cc if already present in cache and but refresh is requested"`).
- are the conditionals making sense? is there anything I missed?
- is there any logic left inside `media_perma_cc_archiver` or `media_archive_org_archiver` …

Update when to archive to archive.org and perma.cc

---

app/models/concerns/media_archive_org_archiver.rb
lib/pender/exception/archive_org_error.rb
lib/pender/exception/too_many_captures.rb
test/models/archiver_test.rb

We created specific errors to Archive.org. We want to make it easier to identify where errors are coming from in Sentry, and what they are related to.
References: TICKET-ID, TICKET-ID, …
I tested this one by raising the errors and checking Sentry.
I wasn't sure if it was needed to add a test here. We have tests that check for how the archivers behave in case of failure, what would we be testing here? If Sentry is notified? So I didn't add one, if you feel we should add a test, I can do so.

Create Archive.org specific errors

---

app/models/concerns/media_archive_org_archiver.rb
config/initializers/03_sidekiq.rb

We were getting some errors on Sentry where we expected the argument to be an Exception, but got NilClass. We think that was happening because some errors where happening during a delayed job (`get_archive_org_status`), so our `handle_archiving_exceptions` wasn't handling those.
Meaning they would be retried multiple times without being re-raised as RetryLater. When they hit the death handler limit_hit_exception would be nil because they would fail `if original_exception.is_a?(Pender::Exception::RetryLater)`
We are now handling errors inside `get_archive_org_status`, but we are adding the else to the death handler as an extra safety measure. We want to see what kind of errors we get for a while and then decide if this i needed or not, and what the best way to handle this is.
References: …

3865 – Fix issue where death handler was getting NilClass instead of Exception

---

app/models/concerns/media_archive_org_archiver.rb
test/models/archiver_test.rb

We split archive org errors into two: Pender::Exception::TooManyCaptures and Pender::Exception::ArchiveOrgError. It makes sense for Pender::Exception::TooManyCaptures to not be retried, but Pender::Exception::ArchiveOrgError should. So we updated `send_to_archive_org` in `media_archive_org_archiver`.
References: 3707
Test "should update media with error when Archive.org can't archive the url" makes sure we are getting the error data when we hit ArchiveOrgError. 
Test "when archive.org fails to archive, it should add to data the available archive.org snapshot (if available) and the error" makes sure we are getting the data (and snapshot) when we hit TooManyCaptures.
The tests here maybe should be renamed, but I'll look into that while going through the tests' refactoring.

Retry ArchiveOrgErrors

---

app/models/concerns/media_perma_cc_archiver.rb
lib/pender/exception/perma_cc_error.rb
test/models/archiver_test.rb

We want PermaCC to have specific errors, like ArchiveOrg, so we can better track and handle errors. So I created PermaCcError, and it's also using TooManyCaptures once we hit it's limit.
Importat: While working on tests I noticed that we were raising RetryLater when we errored in PermaCC, and that was causing it to behave in a different way then expected (it wasn't updating data and notifying the webhook, that would only happen when we hit the retry limit). So we now raise PermaCcError. It's retried, updates data and notifies the webhook.
Besides that, we don't want to retry when the archiving limit is hit. So when we hit TooManyCaptures it updates data and the webhook, but does not retry.
CV2-3886
`test "when Perma.cc fails with Pender::Exception::PermaCcError it should update media with …

3887 – Better error handling in PermaCC

---

app/models/concerns/media_archive_org_archiver.rb
app/models/concerns/media_archiver.rb
app/models/concerns/media_perma_cc_archiver.rb
lib/pender/exception/perma_cc_error.rb
test/models/archiver_test.rb
test/workers/archiver_worker_test.rb

We had a lot of tests that were making real requests that weren't relevant to this test. So we decided to do a refactoring of the tests. What we did:
1. mock all requests
2. add new tests when needed
3. use one setup and teardown for all tests
4. skip tests related to video-archiving (we don't use this feature anymore, it will be dealt with in another ticket)
5. general clean up
While working on the tests there were a few issues that appearead, and I ended up dealing with them here:
1. skip_perma_cc_archiver should return true if key.nil? ([commit](https://github.com/meedan/pender/pull/411/commits/cec003512da8ca2d5232f3e1dca7fe644af8060a))
2. mock perma_cc failed test and fix perma_cc error raising ([commit](https://github.com/meedan/pender/pull/411/commits/ea22647217781834e7f24fcf5380479c …

[wip] 3886 – Clean up archiver tests

---

app/models/concerns/media_archive_org_archiver.rb

Priority reduction
Clients wishing to avoid rate limiting may opt to schedule their change
task at a reduced priority. When the X-Accept-Reduced-Priority request
header is set to a true-ish value (e.g., 1), a client submitting a task
for execution can avoid rate limiting. If the user is being rate limited,
the task will be queued at a reduced priority rather than returning a 429
Too Many Requests.
If priority reduction occurs, the X-Priority-Reduced header is returned
with the 200 OK response. The header value is the task’s reduced priority
number (e.g., -7 or -9).
Clients should be prepared to receive a 429 Too Many Requests even if
the X-Accept-Reduced-Priority header is sent.
https://archive.org/developers/md-write.html#priority-reduction
References: 3909
I ran the acrhiver tests to …

3909 – Add 'X-Priority-Reduced' to Archive.org request

---

app/models/concerns/media_crowdtangle_item.rb
test/models/parser/facebook_item_test.rb

Currently, we only log requests made to Crowdtangle when there is a failure. In this change, we are adding logging whenever we make any request to Crowdtangle. This will make it possible to keep track of how many requests we are doing.
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context – why has this been changed/fixed.
References: CV2-3892
Tested by sending a request to parse a Facebook URL. This should log both successful and failed requests.
Confirm whether the tests in `test/models/parser/facebook_item_test.rb:173-174` are acceptable.

Log all requests made to Crowdtangle

---

.travis.yml
Gemfile
Gemfile.lock
app/models/concerns/media_archive_org_archiver.rb
app/models/metrics.rb
app/sidekiq/archiver_status_job.rb
app/workers/archiver_status_worker.rb
config/initializers/03_sidekiq.rb
docker-compose.yml
test/models/media_test.rb

We updated to Sidekiq 7, but there were some big changes between 6 and 7. So I'm linking the guides and explaining each step that we took.
**Guides**
https://github.com/sidekiq/sidekiq/blob/main/docs/7.0-API-Migration.md
https://github.com/sidekiq/sidekiq/blob/main/docs/7.0-Upgrade.md
**Steps**
1. We had to update Redis (Redis 6.2+ is now required)
a. We already use Redis 6.2.2 on Live and QA
b. We need to update in Pender, but also in Check and Check-Web
c. We need to run integration tests to make sure this doesn't break anything.
2. strict arguments
a. Add strict argument checking [#5071] Sidekiq will now log a warning if JSON-unsafe arguments are passed to perform_async. Add Sidekiq.strict_args!(false) to your initializer to disable this warning. This warning will switch to an …

3480 – Upgrade to Sidekiq 7

---

config/config.yml.example
test/models/metrics_test.rb

While working on updating our ssm values, we came accross the variable facebook_test_app.
WWe only used it in one test, we weren't declaring it in our config file. 
Besides, since we can specify the values by environment, I think the different variable name is not needed.
References: 3875
- Etc.

3875 – Remove facebook_test_app variable

---

app/models/concerns/media_archiver.rb
app/models/media.rb
test/models/archiver_test.rb
test/models/media_test.rb

Add logging for all parser and archiver calls so that we can collect metrics of successful vs failed parser activity.
Fixes: CV2-4107
I confirmed that we are logging any parser and archiver activity as `INFO` entries in the logfiles.
- Confirm that all URL parsing is being logged
- Confirm that all archive calls are being logged

Add logging to parsers and archivers inside media.rb

---

app/models/concerns/request_helper.rb
app/models/oembed_item.rb
test/integration/parsers/page_item_test.rb
test/models/media_test.rb
test/models/oembed_item_test.rb

Catch and log HTTP exceptions when sending oembed requests in order to prevent generic issues in sentry.
- Etc.

Catch and log http errors

---

app/models/oembed_item.rb

When fixing CV2-4053, we broke an existing oembed test where we are now returning `nil` instead of an actual error message. This change is a fix for that break.
References: CV2-4053
I have confirmed that all tests in `oembed_item_test` are passing successfully.
- Confirm that all tests in `oembed_item_test` are passing successfully.

Fix broken oembed_item_test

---

app/sidekiq/archiver_status_job.rb
app/workers/archiver_worker.rb

We want our archive_org jobs to stop retrying too early, both for the `archiver_worker` as for the `archiver_status_job`. This means: 
- waiting at least 5 minutes before retrying a request to save page ([relevant info](https://archive.org/details/toomanyrequests_20191110)) 
- waiting more between retries
- stop retrying if it’s over a too long period of time (the page might change if it takes days to retry)
- consider if we want all archivers to have the same behavior (since both perma and archive use the same job)
Obs.: For both I used sidekiqs own retrying/backing off formula as a starting point.(here)[https://github.com/sidekiq/sidekiq/wiki/Error-Handling#automatic-job-retry]
**`archiver_status_job`**:
- start retrying: aprox. after a minute, that should be more than enough (it …

4076 – Adjust archive_org job retry schedule

---

app/models/metrics.rb
app/workers/metrics_worker.rb
test/models/metrics_test.rb

Context:
* Today, we schedule metrics to be updated for a single URL everyday for a few days. When it fails, this means that the error propagation gets exponential
* We don’t have “metrics on metrics”, so we can’t really compare the number of errors with the number of requests
Scope:
* Log every time metrics are requested, differentiating between first request and updates:
* **In our logs we are already differentiating between first attempt and update numbers by logging the `update_number`. The first attempt is logged as `update_number: 0`. So there was no need to add extra logging.** 
* Reduce the number of times we update metrics
* **Reduced to one update in two days.**
References: 3908
Ran the metrics_test file and updated a test (`rails test test/models/metrics_test.rb:81`).
Also just …

3908 – Improve Metrics Update

---

.github/workflows/ci-test-pr.yml

The github-slack integration is looking for “pull request opened” events
but we had marked the event trigger for the workflow to be on push commits.
they have to match, so we are changing it to the pull_request event trigger
in the test workflow.
We might be able to change it on the slack integration, but I thought it
might be better to keep it the same as presto and timpani.
References: 3875
- Etc.

3875 – Change trigger from push to pull_request

---

Gemfile
Gemfile.lock
test/controllers/medias_controller_test.rb

Upgrade rack-cors to version 2.0.2 or later, as recommended by Dependabot.
Upgrade rack-cors to version 2.0.2 or later, as recommended by Dependabot.
References: https://github.com/meedan/pender/security/dependabot/70
Confirmed that all tests pass

Upgrade rack-cors to version 2.0.2 or later

---

app/models/concerns/provider_twitter.rb
app/models/parser/dropbox_item.rb
app/models/parser/twitter_item.rb
app/models/parser/twitter_profile.rb
test/data/twitter-item-response-success.json
test/integration/parsers/twitter_item_test.rb
test/integration/parsers/twitter_profile_test.rb
test/lib/lapis_webhook_test.rb
test/models/media_test.rb
test/models/parser/dropbox_test.rb
test/models/parser/telegram_test.rb
test/models/parser/twitter_item_test.rb

Embeds for twitter had stopped working. We noticed **two issues**:
1. Some links were being parsed by page, because we were not accounting for 'x.com', only for 'twitter.com'.
2. The way we were creating the embed for twitter items no longer worked, even after fixing the issue above. (Note: creating default pender embeds for twitter items and profile works)
**How it was fixed**
1. Added 'x' to our regex both for item and profile
2. Looked into the twitter embed and updated how we are building it.
References: 4652
Creating an item from twitter locally.
Some tests related to the changes were fixed, BUT some unrelated tests broke as well and had to be fixed.

4652 – Embeds for X (Twitter) links with x.com are not consistently loading for all items

---

Gemfile
Gemfile.lock
app/models/media.rb
config.ru
config/initializers/metrics_registry.rb
lib/metrics_service.rb
test/lib/metrics_service_test.rb
test/models/parser/dropbox_test.rb

- Added the gem `prometheus-client`.
- Created a class abstraction `MetricsService`, so it's easy for us to change between prometheus, otel, or whatever else we might think is best.
- Created some very basic methods to create and increment a custom counter.
- Created one metric `media_request_total` so we can start testing things.
- We create and register custom metrics once on initialization, and then call increment wherever it's needed
- The gem adds `http_server_request_duration_seconds histogram`, `http_server_requests_total counter` and `http_server_exceptions_total counter` by default.
References: 4396, 4518
I added some very basic tests, just to make sure I was implementing the methods correctly. Please suggests any tests you think are needed.
And tested by making requests and …

4518 – Create metrics class abstraction using Prometheus ruby client

---

app/views/medias/index.js.erb

Fixes `Cannot read properties of null (reading 'postMessage')` found on Sentry.
References: CV2-4900
Since the real cause is very hard to reproduce, I just tested manually that the pender embeds are still working after the change.
I also verified compatibility of the safe navigation operator with browsers and it's supported since 2020 in Chrome and Firefox, so I'm assuming it's safe to use, since I don't think there's any sort of backward compatibility preprocessing in Pender.
- Etc.

Add safe navigation operator to fix sentry issue

---

app/models/media.rb
config/initializers/metrics_registry.rb
lib/metrics_service.rb
test/integration/parsers/page_item_test.rb
test/lib/metrics_service_test.rb

We are now sending metrics related to parsing requests. We are keeping track of: service_name, parser_name, parsed_host and parsing_status.
What we want to answer:
1. total of parsing requests per x amount of time
2. total of parsing requests per x amount of time grouped by partner [TBD: not possible to do right now]
3. total of parsing requests per x amount of time grouped by parser
4. total of parsing requests of an unique host, which does not have a dedicated parser, per x amount of time
5. total of errors and total of successes of our parsing requests per x amount of time
References: 4396, 4520
By building the boards, and making sure the data is getting to Honeycomb.
I ended up splitting the metrics so we can get more granular data and more generic data. I did this because it was …

4520 – Add metrics to code and create Honeycomb status dashboard: parser requests [WIP]

---

app/models/media.rb

While looking at logs for webhook notification errors I thought it could be helpful:
- to add a log when we hit a Net::HTTPException error
- to add '[Webhook Notification]' so it is easier to group them if we want to
References: 4228
- Etc.

Add log to notify webhook

---

test/lib/lapis_webhook_test.rb

Fixing a test that is currently failing on CI. The URL used in the test doesn't work anymore, so I replaced by another one.
References: No Jira ticket created for this.
The test that was failing is passing now:
```
ruby test/lib/lapis_webhook_test.rb -n test_should_notify
Finished in 1.635062s, 0.6116 runs/s, 0.6116 assertions/s.
1 runs, 1 assertions, 0 failures, 0 errors, 0 skips
```

Fixing test

---

app/models/parser/facebook_item.rb
test/models/parser/facebook_item_test.rb

Change conditions for when fb embed is shown, and add tests to ensure all viable URLs return embeds.
References: CV2-5257
Tested by ensuring embed shows locally, and also that the tests are passing.

Correctly show facebook embed

---

.github/workflows/ci-test-pr.yml

Fixes the steps that generate and upload the code coverage report to Code Climate.
The main issue was that previously, we ran the tests, prepared the coverage report, and uploaded it all within the Docker container. Now, however, the tests run inside the Docker container, while the coverage report is prepared outside of it, leading to a mismatch in file paths. The solution I implemented was to use sed to replace the paths, changing `/app/pender` to `/home/runner/work/pender`. I also needed to copy `codeclimate.json` to the coverage directory and set the `$CC_TEST_REPORTER_ID` environment variable.
Reference: CV2-5020.
Code Coverage report was generated and uploaded to Code Climate as expected:

Fixing issues with code coverage report generation and upload to Code Climate

---

app/models/media.rb
app/models/parser/instagram_profile.rb
test/integration/parser/page_item_test.rb

We have a bunch of tests that are failing, mostly related to URL normalization.
The main issue is that sometimes, [get_cannonical_url](https://github.com/meedan/pender/blob/develop/app/models/media.rb#L204) was returning `true` instead of a valid URL, which then confused any methods that read the URL after this point.
Confirmed that tests pass, and that URL normalization is working as expected.
Check whether any tests failed.

Fix broken tests

---

app/models/oembed_item.rb
test/models/oembed_item_test.rb

Currently, we are returning an exception instead of raising it.
References: CV2-6027
- Ensured that any exception when fetching oembeds is raised
- Added a test to verify and enforce this

Raise exceptions when errors occur while fetching oembed data

---

app/sidekiq/archiver_status_job.rb

When looking through Sentry errors we thought we could maybe look into the retry intervals and duration, and see if there was anything to update.
Before we would wait 1 minute to start, I think we could increase it. So I copied the both the start and interval from the archiver_worker. We wait longer to start and between retries.
References: CV2-6037
- Etc.

6037 – Increase interval between retries

---

app/models/concerns/media_archive_org_archiver.rb
lib/pender/exception/blocked_url.rb
test/models/archiver_test.rb

When an URL can't be captured ArchiveOrg might send one of the following:
```
{
message: This URL is in the Save Page Now service block list and cannot be captured. Please email us at "info@archive.org" if you would like to discuss this more.,
status: error,
status_ext: error:blocked-url
}
```
```
{
message: We’re currently facing some limitations when it comes to archiving this site. We apologize for any inconvenience this might cause and appreciate your understanding. Please email us at "info@archive.org" if you would like to discuss this more.,
status: error,
status_ext: error:blocked-url
}
```
In both cases, it doesn't make sense for us to retry. We can treat this as a custom exception (`Pender::Exception::BlockedUrl`) and just notify Sentry.
References: CV2-6000
I added a test  and …

6000 – Handle ArchiveOrg error:blocked-url

---

config/initializers/metrics_registry.rb

For historical reasons `realoder.to_prepare` might run twice, we have had that happen in local development. When that happens it tries to register the custom_counter again, which causes an error: `/usr/local/bundle/gems/prometheus-client-4.2.3/lib/prometheus/client/registry.rb:26:in block in register': pender_parser_requests_total has already been registered (Prometheus::Client::Registry::AlreadyRegisteredError)`
So we changed this to ensure this only runs once.
References: CV2-6157
This error happened a few times for me and for Jay, but we I tried to test it, I was not able to manually reproduce it. I did make sure that metrics were running as expected, by making a few requests and looking at `localhost:3200/metrics` to make sure it was being updated correctly.
Please describe parts of …

6157 – Deal with Prometheus `has already been registered` error

---

docker-compose.yml

Removed the top-level `version` attribute since it  is obsolete:
`the attribute version is obsolete,it will be ignored, please remove it to avoid potential confusion`
https://docs.docker.com/reference/compose-file/version-and-name/#version-top-level-element-obsolete
References: CV2-6163
- Etc.

6163 – Remove deprecated version attribute

---

test/integration/parser/facebook_item_test.rb
test/integration/parser/facebook_profile_test.rb

A couple tests started failing because the url now has a query appended. Since this isn't an issue we are just updating the tests to be less specific.
```
Failure:
FacebookItemIntegrationTest#test_should_return_data_even_if_post_does_not_exist [/app/test/integration/parser/facebook_item_test.rb:38]:
--- expected
+++ actual
@@ -1 +1 @@
-"https://www.facebook.com/111111111111111/posts/1111111111111111"
+"https://web.facebook.com/111111111111111/posts/1111111111111111?absolute_url_processed=1&_rdc=1&_rdr"
Failure:
FacebookProfileIntegrationTest#test_should_return_data_even_if_Facebook_page_does_not_exist [/app/test/integration/parser/facebook_profile_test.rb:39]:
--- expected
+++ actual
@@ -1 +1 @@
-"https://www.facebook.com/pages/fakepage/1111111111111" …
```

CV2-6208 – Update Facebook tests

---

.github/workflows/ci-test-pr.yml

There are two dependabot PRs failing with this error:
```
mv: cannot stat '/tmp/.buildx-cache-new': No such file or directory
Error: Process completed with exit code 1.
```
This PR tries to fix it.
References: No Jira ticket associated. Dependabot PRs mentioned above:
- https://github.com/meedan/pender/actions/runs/13766044983/job/38492640142?pr=527
- https://github.com/meedan/pender/actions/runs/13766049113/job/38492651335?pr=526
The error above should be gone.

Fixing CI error by making sure that directory exists before trying to rename it

---

app/models/concerns/media_archive_org_archiver.rb
app/models/concerns/media_archiver.rb
lib/pender/exception/item_not_available.rb
test/models/archiver_test.rb

- Sometimes ArchiveOrg will send a HTML response: 
- which are usually issues on their side like: “429 Too Many Requests” and “Item Not Avaiable”, 
- but also caused an error on our side, since we always expected a JSON.
- We have two jobs that run for ArchiveOrg, both make requests, so this happens at different places/time, but need very similar error handling.
- We also wanted to take this opportunity to try to centralize more our error handling.
- Handling HTML errors
- I extracted a method `json_parse` we can use for our both requests. It rescues JSON::ParserError, and re-raises it as a more specific error or as itself.
- Then `handle_archiving_exceptions` deals with it.
- Other errors
- To make this more cohesive, I updated this to have the same behavior as when we are dealing with …

4482 – Handle Archive.org HTML errors

---

app/models/concerns/provider_facebook.rb
test/models/parser/facebook_item_test.rb

A facebook video from facebook watch was sometimes redirecting to the main watch page. Meaning we were getting pretty generic content, like:
- url: `https://www.facebook.com/watch/`
- title: `"Discover Popular Videos"`
This caused `This item already exists` to be raised for different items. So, if an url redirects to the main watch page, we want the title and url to be the url from the request.
References: 6357
```ruby
rails test test/models/parser/facebook_item_test.rb:568
rails test test/models/parser/facebook_item_test.rb:568
```
I think we might want to change `set_facebook_privacy_error` method name and its error message, or at least the error message. 
https://github.com/meedan/pender/blob/903c7f244c8f5cec748c4c92f11f68ec37fa0c10/app/models/concerns/provider_facebook.rb#L84-L103 …

6357 – Fix how we parse a generic Facebook watch page

---

app/models/concerns/media_apify_item.rb
app/models/concerns/provider_facebook.rb

We have been running into some Gateway time-out and Net::ReadTimeout errors, in QA and Live, that seem connected to the apify request. So we are adding read_timeout to the request.
References: CV2-5999
- Etc.

5999 – Add timeout to apify request

---

app/helpers/medias_helper.rb
app/models/concerns/request_helper.rb
test/models/media_test.rb

If the author or author_picture urls are invalid, we should not stop the
item from being parsed.
I thought the best way to handle this was to create a new method
`parse_nonmandatory_url` in the `RequestHelper` module. This
way, we can safely attempt to parse URLs that might not be critical
to the media item.
It is only a wrapper around the existing `parse_url` method, so if there
are changes to parsing itself, we should only need to update
`parse_url`.
References: CV2-6414
```ruby
rails test test/models/media_test.rb:643
```
- Etc.

6414 – The failed parsing of author_picture or picture urls should not stop the creation of an item

---

app/models/concerns/media_apify_item.rb
test/models/parser/facebook_item_test.rb

We need to set the parsed_response variable before raising `ApifyResponseError`. 
I'm also parsing the Apify response, so we can have a better formatting for the data in Sentry.
References: CV2-5814
```ruby
bin/rails test test/models/parser/facebook_item_test.rb
bin/rails test test/models/parser/instagram_item_test.rb
```
- Etc.

5814 – fix apify sentry notification

---

app/models/concerns/media_apify_item.rb
test/models/media_apify_item_test.rb
test/models/parser/facebook_item_test.rb

Most of the time, it seems the Apify response is an array with a hash,
but sometimes it can be a hash. Which was causing a TypeError. E.g.:
`a = {a: 1}.first` returns `[:a, 1]`
`a[:a]` returns `no implicit conversion of Symbol into Integer (TypeError)`
References: CV2-6460
```
rails test test/models/media_apify_item_test.rb
```
- Etc.

handle_apify_error method should not fail when the parsed_response is a hash

---

app/models/media.rb
app/models/parser/twitter_item.rb

The OpenURI request fails with a 400, because there is authorization that
is specific to the Twitter parser, that Media does not have access to.
So since we know this will fail, we skip it. But it is another sign
that this is Parser logic inside of Media, and it needs to be refactored.
References: CV2-6504
- Etc.

6504 – Skip get_canonical_url for Twitter items

---

test/test_helper.rb

I ran again into issues when testing due to unexpected cache being available. I realized that instead of `Rails.cache.clear`, I should probably be using `clear_bucket`. 
We already called this method in the bigger setup and teardown, but we should also call it in isolated_setup and isolated_teardown.
Relates to https://github.com/meedan/pender/pull/585
- Etc.

Fix test caching issue: use clear_bucket instead of Rails.cache.clear

---

config/environments/test.rb

Specially when testing individual tests, it's useful to have more detailed logs.
But we don't need those in CI, and probably don't need them all the time in local testing either.

Update test environment logging settings
